# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Stage 1: build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
# Skip NSwag generation on Linux by marking CI environment
ENV CI=true

# Copy csproj and restore dependencies
COPY src/YnabMcpServer/YnabMcpServer.csproj src/YnabMcpServer/
RUN dotnet restore src/YnabMcpServer/YnabMcpServer.csproj

# Copy everything else and publish
COPY . .
RUN dotnet publish src/YnabMcpServer/YnabMcpServer.csproj -c Release -o /app/publish

# Stage 2: runtime
FROM mcr.microsoft.com/dotnet/runtime:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "YnabMcpServer.dll"]
