@baseUrl = https://api.youneedabudget.com/v1
@apiToken = {{$dotenv YNAB_API_TOKEN}}
@budgetId = {{$dotenv BUDGET_ID}}

# @name getUser
### Get User Info
GET {{baseUrl}}/user
Authorization: Bearer {{apiToken}}

# @name getBudgets
### Get All Budgets
GET {{baseUrl}}/budgets
Authorization: Bearer {{apiToken}}

# @name getBudgetDetails
### Get Budget Details
GET {{baseUrl}}/budgets/{{budgetId}}
Authorization: Bearer {{apiToken}}
