@baseUrl = https://api.youneedabudget.com/v1
@apiKey = {{$dotenv YNAB_API_KEY}}
@budgetId = {{$dotenv BUDGET_ID}}

# @name getUser
### Get User Info
GET {{baseUrl}}/user
Authorization: Bearer {{apiKey}}

# @name getBudgets
### Get All Budgets
GET {{baseUrl}}/budgets
Authorization: Bearer {{apiKey}}

# @name getBudgetDetails
### Get Budget Details
GET {{baseUrl}}/budgets/{{budgetId}}
Authorization: Bearer {{apiKey}}
